const translations = {
  fr: {
    htmlLang: "fr", dir: "ltr",
    topbarMessage: "Club communautaire, culture sportive et ambition locale.",
    brandName: "Coopération Olad Fkira",
    brandSubtitle: "Club de football et vie associative",
    navAbout: "À propos", navCompetitions: "Compétitions", navGallery: "Galerie", navContact: "Contact",
    heroEyebrow: "Village, jeunesse et football",
    heroTitle: "Un site moderne pour faire rayonner le club de Coopération Olad Fkira.",
    heroText: "Cette vitrine met en avant l'équipe, l'esprit associatif et les événements sportifs qui rassemblent les joueurs, les familles et les supporters autour du football.",
    heroPrimary: "Découvrir le club", heroSecondary: "Voir les activités",
    stat1Value: "Association", stat1Label: "Sport, culture et développement",
    stat2Value: "Jeunesse", stat2Label: "Encadrement et esprit d'équipe",
    stat3Value: "Village", stat3Label: "Ancrage local et mobilisation",
    heroNoteEyebrow: "Identité du club", heroNoteTitle: "Une présence digitale plus claire pour présenter l'équipe.",
    aboutEyebrow: "Présentation", aboutTitle: "Un club né de la vie associative, du sport et de l'engagement local.",
    aboutCard1Title: "L'équipe",
    aboutCard1Text: "Coopération Olad Fkira représente une dynamique de proximité où les joueurs portent les couleurs du village avec fierté, solidarité et discipline.",
    aboutCard2Title: "La mission",
    aboutCard2Text: "Le projet sportif s'inscrit dans une vision plus large: soutenir la jeunesse, encourager la pratique du football et renforcer les liens entre les habitants.",
    aboutCard3Title: "Les valeurs",
    aboutCard3Text: "Respect, travail collectif, progression et attachement au territoire sont au cœur de l'identité du club.",
    competitionsEyebrow: "Tournois et participation",
    competitionsTitle: "Des rencontres sportives qui font vivre le football local.",
    competition1Kicker: "Participation", competition1Title: "Matchs et tournois de proximité",
    competition1Text: "Le club prend part à des rencontres amicales et à des compétitions locales, avec l'objectif de faire progresser l'équipe et de représenter dignement Olad Fkira.",
    competition2Kicker: "Organisation", competition2Title: "Événements sportifs communautaires",
    competition2Text: "Dans l'esprit associatif du village, le club contribue à l'organisation d'activités sportives, de journées de football et d'animations qui rassemblent joueurs et supporters.",
    competition3Kicker: "Ambition", competition3Title: "Développer la visibilité du club",
    competition3Text: "Cette plateforme est pensée pour mieux communiquer sur les matchs, les tournois, les participations futures et les temps forts de la saison.",
    finalEyebrow: "Dernière compétition", finalTitle: "La finale s'est jouée jusqu'au bout face à Lmzawir.",
    finalScoreLabel: "Score final", finalScore: "0 - 1",
    finalOpponentTitle: "Finale contre Lmzawir",
    finalText: "Le club a atteint la finale de la dernière compétition. Le match s'est terminé sur une défaite honorable 1-0 contre Lmzawir, après un parcours qui a porté haut les couleurs d'Olad Fkira.",
    finalNote: "La vidéo partagée montre surtout l'ambiance, les moments marquants de la finale et la cérémonie de clôture.",
    finalVideoButton: "Voir la vidéo de la finale",
    videoCaptionEyebrow: "Vidéo Facebook",
    videoCaptionText: "Couverture spéciale de l'ambiance de la finale, de la remise du titre et des réactions après match.",
    highlightsEyebrow: "Ce que le site peut montrer", highlightsTitle: "Une base professionnelle à enrichir au fil des saisons.",
    highlight1Title: "Actualités du club", highlight1Text: "Résultats, convocations, annonces et photos des matchs à venir.",
    highlight2Title: "Histoire et palmarès", highlight2Text: "Tournois organisés, participations importantes et moments marquants du club.",
    highlight3Title: "Vie associative", highlight3Text: "Initiatives locales, soutien à la jeunesse et mobilisation du village.",
    galleryEyebrow: "Galerie", galleryTitle: "Première galerie inspirée des visuels publics du club.",
    galleryCaption: "Image publique récupérée depuis la page Facebook du club.",
    galleryPhoto1: "Coup d'envoi et concentration des joueurs sur le terrain.",
    galleryPhoto2: "Photo souvenir autour du trophée après la compétition.",
    galleryPhoto3: "L'équipe réunie avant ou après la rencontre.",
    galleryPhoto4: "Des supporters et des jeunes présents pour accompagner le club.",
    panelEyebrow: "Nom officiel",
    officialNameText: "Le site présente le club sous l'appellation simple “Coopération Olad Fkira” tout en conservant le nom officiel visible publiquement.",
    sourceEyebrow: "Source utilisée", sourceText: "Les éléments visuels et le nom officiel proviennent de la page Facebook publique partagée par vos soins.",
    contactEyebrow: "Contact", contactTitle: "Une présence en ligne prête à évoluer avec le club.",
    contactCard1Title: "Page Facebook", contactCard1Text: "Pour suivre l'activité du club, consulter les publications et garder le lien avec la communauté.",
    contactFacebook: "Ouvrir la page",
    contactCard2Title: "Évolution du site", contactCard2Text: "On peut ensuite ajouter de vraies photos de matchs, les résultats, l'effectif et le calendrier.",
    contactButton: "Version vitrine prête"
  },
  en: {
    htmlLang: "en", dir: "ltr",
    topbarMessage: "A community club built on sport, local pride and collective energy.",
    brandName: "Cooperation Olad Fkira",
    brandSubtitle: "Football club and community life",
    navAbout: "About", navCompetitions: "Competitions", navGallery: "Gallery", navContact: "Contact",
    heroEyebrow: "Village, youth and football",
    heroTitle: "A modern website to showcase the Cooperation Olad Fkira club.",
    heroText: "This website highlights the team, the community spirit and the football events that bring together players, families and supporters.",
    heroPrimary: "Discover the club", heroSecondary: "See activities",
    stat1Value: "Association", stat1Label: "Sport, culture and development",
    stat2Value: "Youth", stat2Label: "Guidance and team spirit",
    stat3Value: "Village", stat3Label: "Local roots and mobilization",
    heroNoteEyebrow: "Club identity", heroNoteTitle: "A clearer digital presence to present the team.",
    aboutEyebrow: "Overview", aboutTitle: "A club shaped by community work, sport and local commitment.",
    aboutCard1Title: "The team",
    aboutCard1Text: "Cooperation Olad Fkira reflects a local dynamic where players carry the village colors with pride, solidarity and discipline.",
    aboutCard2Title: "The mission",
    aboutCard2Text: "The sporting project fits into a broader vision: supporting youth, encouraging football practice and strengthening ties between residents.",
    aboutCard3Title: "Values",
    aboutCard3Text: "Respect, teamwork, progress and attachment to the local area are central to the club identity.",
    competitionsEyebrow: "Tournaments and participation",
    competitionsTitle: "Sporting encounters that keep local football alive.",
    competition1Kicker: "Participation", competition1Title: "Local matches and tournaments",
    competition1Text: "The club takes part in friendly games and local competitions, aiming to improve the team and proudly represent Olad Fkira.",
    competition2Kicker: "Organization", competition2Title: "Community sporting events",
    competition2Text: "In the association spirit of the village, the club contributes to football days, sporting activities and community gatherings for players and supporters.",
    competition3Kicker: "Ambition", competition3Title: "Building the club's visibility",
    competition3Text: "This platform is designed to communicate more clearly about matches, tournaments, future participation and season highlights.",
    finalEyebrow: "Latest competition", finalTitle: "The final was fought to the end against Lmzawir.",
    finalScoreLabel: "Final score", finalScore: "0 - 1",
    finalOpponentTitle: "Final against Lmzawir",
    finalText: "The club reached the final of the latest competition. The match ended in a narrow 1-0 loss to Lmzawir after a strong run that proudly represented Olad Fkira.",
    finalNote: "The shared video mainly captures the final atmosphere, important highlights and the closing ceremony.",
    finalVideoButton: "Watch the final video",
    videoCaptionEyebrow: "Facebook video",
    videoCaptionText: "Special coverage of the final atmosphere, trophy ceremony and post-match reactions.",
    highlightsEyebrow: "What the website can show", highlightsTitle: "A professional foundation that can grow season after season.",
    highlight1Title: "Club news", highlight1Text: "Results, announcements, selections and upcoming match photos.",
    highlight2Title: "History and honors", highlight2Text: "Organized tournaments, important participation and memorable club moments.",
    highlight3Title: "Community life", highlight3Text: "Local initiatives, youth support and village mobilization.",
    galleryEyebrow: "Gallery", galleryTitle: "An initial gallery inspired by the club's public visuals.",
    galleryCaption: "Public image retrieved from the club's Facebook page.",
    galleryPhoto1: "Kick-off and player focus on the pitch.",
    galleryPhoto2: "A memory photo with the trophy after the competition.",
    galleryPhoto3: "The team gathered before or after the match.",
    galleryPhoto4: "Supporters and local youth present to back the club.",
    panelEyebrow: "Official name",
    officialNameText: "The website uses the simple public label “Cooperation Olad Fkira” while keeping the official name visible.",
    sourceEyebrow: "Source used", sourceText: "The visual material and official name come from the public Facebook page you shared.",
    contactEyebrow: "Contact", contactTitle: "An online presence ready to grow with the club.",
    contactCard1Title: "Facebook page", contactCard1Text: "Follow the club activity, browse posts and stay connected with the community.",
    contactFacebook: "Open the page",
    contactCard2Title: "Future site upgrade", contactCard2Text: "We can next add real match photos, results, the squad list and a fixture calendar.",
    contactButton: "Showcase version ready"
  },
  ar: {
    htmlLang: "ar", dir: "rtl",
    topbarMessage: "نادي مجتمعي يجمع بين الرياضة وروح القرية وطموح الشباب.",
    brandName: "تعاون أولاد افقيرة",
    brandSubtitle: "نادي كرة القدم والحياة الجمعوية",
    navAbout: "عن الفريق", navCompetitions: "المنافسات", navGallery: "المعرض", navContact: "التواصل",
    heroEyebrow: "القرية والشباب وكرة القدم",
    heroTitle: "موقع حديث للتعريف بفريق تعاون أولاد افقيرة وإبراز حضوره.",
    heroText: "هذا الموقع يقدم الفريق وروح العمل الجمعوي والأنشطة الكروية التي تجمع اللاعبين والعائلات والمشجعين حول كرة القدم.",
    heroPrimary: "اكتشف النادي", heroSecondary: "شاهد الأنشطة",
    stat1Value: "جمعية", stat1Label: "الرياضة والثقافة والتنمية",
    stat2Value: "الشباب", stat2Label: "التأطير وروح الفريق",
    stat3Value: "القرية", stat3Label: "الارتباط المحلي والتعبئة",
    heroNoteEyebrow: "هوية النادي", heroNoteTitle: "حضور رقمي أوضح لتقديم الفريق بشكل أفضل.",
    aboutEyebrow: "تقديم", aboutTitle: "فريق وُلد من روح العمل الجمعوي والرياضة والانخراط المحلي.",
    aboutCard1Title: "الفريق",
    aboutCard1Text: "يعكس تعاون أولاد افقيرة دينامية محلية يحمل فيها اللاعبون ألوان القرية بفخر وتضامن وانضباط.",
    aboutCard2Title: "الرسالة",
    aboutCard2Text: "المشروع الرياضي جزء من رؤية أوسع تهدف إلى دعم الشباب وتشجيع ممارسة كرة القدم وتقوية الروابط بين السكان.",
    aboutCard3Title: "القيم",
    aboutCard3Text: "الاحترام والعمل الجماعي والتطور والارتباط بالمجال كلها قيم أساسية في هوية النادي.",
    competitionsEyebrow: "الدورات والمشاركة", competitionsTitle: "لقاءات رياضية تنعش كرة القدم المحلية وتجمع المجتمع.",
    competition1Kicker: "مشاركة", competition1Title: "مباريات ودورات محلية",
    competition1Text: "يشارك النادي في مباريات ودية ومنافسات محلية بهدف تطوير الفريق وتمثيل أولاد افقيرة بأفضل صورة.",
    competition2Kicker: "تنظيم", competition2Title: "أنشطة رياضية مجتمعية",
    competition2Text: "في إطار الروح الجمعوية للقرية يساهم النادي في تنظيم أيام رياضية وأنشطة كروية ولقاءات تجمع اللاعبين والجمهور.",
    competition3Kicker: "طموح", competition3Title: "تعزيز حضور النادي",
    competition3Text: "صُممت هذه المنصة لتحسين التواصل حول المباريات والدورات والمشاركات المقبلة وأبرز لحظات الموسم.",
    finalEyebrow: "آخر منافسة", finalTitle: "اللعب استمر حتى النهاية في المباراة النهائية أمام لمزاوير.",
    finalScoreLabel: "النتيجة النهائية", finalScore: "0 - 1",
    finalOpponentTitle: "النهائي ضد لمزاوير",
    finalText: "وصل النادي إلى نهائي آخر منافسة، وانتهت المباراة بهزيمة مشرفة بهدف دون رد أمام لمزاوير بعد مشوار قوي رفع اسم أولاد افقيرة عالياً.",
    finalNote: "الفيديو المشارك يبرز أجواء النهائي واللحظات المهمة وحفل الاختتام.",
    finalVideoButton: "شاهد فيديو النهائي",
    videoCaptionEyebrow: "فيديو فيسبوك",
    videoCaptionText: "تغطية خاصة لأجواء النهائي والتتويج وردود الفعل بعد المباراة.",
    highlightsEyebrow: "ما الذي يمكن أن يعرضه الموقع", highlightsTitle: "قاعدة احترافية يمكن تطويرها مع مرور المواسم.",
    highlight1Title: "أخبار النادي", highlight1Text: "النتائج والإعلانات والاستدعاءات وصور المباريات القادمة.",
    highlight2Title: "التاريخ والإنجازات", highlight2Text: "الدورات المنظمة والمشاركات المهمة واللحظات البارزة في مسار النادي.",
    highlight3Title: "الحياة الجمعوية", highlight3Text: "المبادرات المحلية ودعم الشباب وتعبئة أبناء القرية.",
    galleryEyebrow: "المعرض", galleryTitle: "معرض أولي مستوحى من الصور العمومية الخاصة بالنادي.",
    galleryCaption: "صورة عمومية تم استخراجها من صفحة النادي على فيسبوك.",
    galleryPhoto1: "لحظة انطلاق المباراة وتركيز اللاعبين داخل الملعب.",
    galleryPhoto2: "صورة تذكارية مع الكأس بعد نهاية المنافسة.",
    galleryPhoto3: "صورة جماعية للفريق قبل أو بعد المباراة.",
    galleryPhoto4: "حضور للمشجعين والشباب من أجل مساندة النادي.",
    panelEyebrow: "الاسم الرسمي",
    officialNameText: "يعرض الموقع اسم النادي بصيغة مبسطة مع الحفاظ على الاسم الرسمي الظاهر بشكل عمومي.",
    sourceEyebrow: "المصدر المستعمل", sourceText: "الاسم الرسمي والعناصر البصرية المعروضة هنا مأخوذة من الصفحة العمومية التي شاركتها.",
    contactEyebrow: "التواصل", contactTitle: "حضور رقمي جاهز للتطور مع النادي.",
    contactCard1Title: "صفحة فيسبوك", contactCard1Text: "لمتابعة أنشطة النادي والاطلاع على المنشورات والحفاظ على الصلة مع المجتمع.",
    contactFacebook: "فتح الصفحة",
    contactCard2Title: "تطوير الموقع", contactCard2Text: "يمكننا لاحقاً إضافة صور حقيقية للمباريات والنتائج ولائحة اللاعبين وبرنامج المباريات.",
    contactButton: "النسخة التعريفية جاهزة"
  }
};

const bindings = {
  topbarMessage: "topbar-message", brandName: "brand-name", brandSubtitle: "brand-subtitle",
  navAbout: '[data-nav="about"]', navCompetitions: '[data-nav="competitions"]', navGallery: '[data-nav="gallery"]', navContact: '[data-nav="contact"]',
  heroEyebrow: "hero-eyebrow", heroTitle: "hero-title", heroText: "hero-text", heroPrimary: "hero-primary", heroSecondary: "hero-secondary",
  stat1Value: "stat-1-value", stat1Label: "stat-1-label", stat2Value: "stat-2-value", stat2Label: "stat-2-label", stat3Value: "stat-3-value", stat3Label: "stat-3-label",
  heroNoteEyebrow: "hero-note-eyebrow", heroNoteTitle: "hero-note-title",
  aboutEyebrow: "about-eyebrow", aboutTitle: "about-title", aboutCard1Title: "about-card-1-title", aboutCard1Text: "about-card-1-text", aboutCard2Title: "about-card-2-title", aboutCard2Text: "about-card-2-text", aboutCard3Title: "about-card-3-title", aboutCard3Text: "about-card-3-text",
  competitionsEyebrow: "competitions-eyebrow", competitionsTitle: "competitions-title", competition1Kicker: "competition-1-kicker", competition1Title: "competition-1-title", competition1Text: "competition-1-text", competition2Kicker: "competition-2-kicker", competition2Title: "competition-2-title", competition2Text: "competition-2-text", competition3Kicker: "competition-3-kicker", competition3Title: "competition-3-title", competition3Text: "competition-3-text",
  finalEyebrow: "final-eyebrow", finalTitle: "final-title", finalScoreLabel: "final-score-label", finalScore: "final-score", finalOpponentTitle: "final-opponent-title", finalText: "final-text", finalNote: "final-note", finalVideoButton: "final-video-button", videoCaptionEyebrow: "video-caption-eyebrow", videoCaptionText: "video-caption-text",
  highlightsEyebrow: "highlights-eyebrow", highlightsTitle: "highlights-title", highlight1Title: "highlight-1-title", highlight1Text: "highlight-1-text", highlight2Title: "highlight-2-title", highlight2Text: "highlight-2-text", highlight3Title: "highlight-3-title", highlight3Text: "highlight-3-text",
  galleryEyebrow: "gallery-eyebrow", galleryTitle: "gallery-title", galleryCaption: "gallery-caption", galleryPhoto1: "gallery-photo-1", galleryPhoto2: "gallery-photo-2", galleryPhoto3: "gallery-photo-3", galleryPhoto4: "gallery-photo-4", panelEyebrow: "panel-eyebrow", officialNameText: "official-name-text", sourceEyebrow: "source-eyebrow", sourceText: "source-text",
  contactEyebrow: "contact-eyebrow", contactTitle: "contact-title", contactCard1Title: "contact-card-1-title", contactCard1Text: "contact-card-1-text", contactFacebook: "contact-facebook", contactCard2Title: "contact-card-2-title", contactCard2Text: "contact-card-2-text", contactButton: "contact-button"
};

const langButtons = document.querySelectorAll(".lang-btn");

function setText(target, value) {
  if (target.startsWith("[")) {
    document.querySelectorAll(target).forEach((node) => { node.textContent = value; });
    return;
  }
  const element = document.getElementById(target);
  if (element) element.textContent = value;
}

function applyLanguage(lang) {
  const data = translations[lang];
  document.documentElement.lang = data.htmlLang;
  document.documentElement.dir = data.dir;
  document.body.classList.toggle("rtl", data.dir === "rtl");
  Object.entries(bindings).forEach(([key, target]) => setText(target, data[key]));
  langButtons.forEach((button) => button.classList.toggle("active", button.dataset.lang === lang));
}

langButtons.forEach((button) => {
  button.addEventListener("click", () => applyLanguage(button.dataset.lang));
});

applyLanguage("fr");
